environment             = "dev"
project_id              = "archie-458607"
location                = "europe-west6"
region                  = "europe-west6"
tf_state_bucket         = "terraform-state-dev-851493899554"
storage_bucket          = "archiemcp-dev"
cloudfunction           = "archie-mcp-dev"
# archie_mcp_image_uri   = "europe-west6-docker.pkg.dev/archie-458607/archie-mcp-dev/archiefunct:latest"