environment         = "qa"
project_id          = "archie-458607"
location            = "europe-west6"
region              = "europe-west6"
storage_bucket      = "archiemcp-qa"
cloudfunction       = "archie-mcp-qa"