name: Deploy Infra

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main
      - qa
      - dev
    # Uncomment and adjust paths if you only want the workflow to run
    # when specific files change.
    # paths:
    #   - infra/**
    #   - frontend/**
    #   - backend/**
    #   - .github/workflows/** # Keep this path if you uncomment others

permissions:
  id-token: write
  contents: read # To checkout the repository
# secrets: write # To update repository secrets

jobs:

  prepare_backend:
    name: Deploy Backend
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    env:
      # Google Cloud Authentication Secrets (fetched from environment secrets)
      GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_MCP_SERVICE_ACCOUNT: ${{ secrets.GCP_MCP_SERVICE_ACCOUNT }}
      GCP_COMPUTE_SERVICE_ACCOUNT: ${{ secrets.GCP_COMPUTE_SERVICE_ACCOUNT }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} # Used for bucket project
      GCP_REGION: ${{ vars.GCP_REGION_EU }}

      # Dynamic Terraform State Bucket variable (includes environment name and project number secret)
      TF_STATE_BUCKET: terraform-state-${{ github.ref_name }}-${{ secrets.GCP_PROJECT_NUMBER }}
      ENVIRONMENT: ${{ github.ref_name }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        id: auth
        with:
          workload_identity_provider: ${{ env.GCP_WIF_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

#     - name: Create Service Account (if not exists)
#       run: |
#         TERRAFORM_SA_NAME="archiefunct-dev-sa"  # Name Terraform will use
#         TERRAFORM_SA_EMAIL="${TERRAFORM_SA_NAME}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
#          if gcloud iam service-accounts describe $TERRAFORM_SA_EMAIL --project=${{ secrets.GCP_PROJECT_ID }} > /dev/null 2>&1; then
#           echo "Service account $TERRAFORM_SA_EMAIL already exists (likely created by Terraform in a previous run). Skipping creation."
#         else
#           echo "Service account $TERRAFORM_SA_EMAIL does not exist. Creating..."
#           gcloud iam service-accounts create $TERRAFORM_SA_NAME \
#             --description="Service Account for Cloud Functions" \
#             --display-name="Cloud Functions SA" \
#             --project="${{ secrets.GCP_PROJECT_ID }}"  # Explicitly specify project ID
#           echo "created=true" >> $GITHUB_OUTPUT
#         fi

      - name: Grant MCP SA Permissions to Act As Terraform SA
        run: |
          gcloud projects add-iam-policy-binding ${{ env.GCP_PROJECT_ID }} \
            --member="serviceAccount:${{ env.GCP_MCP_SERVICE_ACCOUNT }}" \
            --role="roles/iam.serviceAccountUser"


      - name: Grant permissions to SA for Cloud Functions
        run: |
          gcloud projects add-iam-policy-binding ${{ env.GCP_PROJECT_ID }} \
            --member="serviceAccount:${{ env.GCP_SERVICE_ACCOUNT }}" \
            --role="roles/serviceusage.serviceUsageAdmin"
      
      - name: grant service account permissions
        run: |
          gcloud projects add-iam-policy-binding ${{ env.GCP_PROJECT_ID }} \
            --member="serviceAccount:${{ env.GCP_SERVICE_ACCOUNT }}" \
            --role="roles/cloudfunctions.developer"

      - name: Grant Cloud Run Admin Role
        run: |
          gcloud projects add-iam-policy-binding ${{ secrets.GCP_PROJECT_ID }} \
            --member="serviceAccount:${{ env.GCP_SERVICE_ACCOUNT }}" \
            --role="roles/run.admin"

      - name: Grant Artifact Registry Repo Admin Role
        run: |
          gcloud projects add-iam-policy-binding ${{ secrets.GCP_PROJECT_ID }} \
            --member="serviceAccount:${{ env.GCP_SERVICE_ACCOUNT }}" \
            --role="roles/artifactregistry.repoAdmin"

      - name: Activate Artifact Registry API
        run: |
          gcloud services enable artifactregistry.googleapis.com \
            --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Create Artifact Registry Repository
        run: |
          REPO_NAME="archie-backend"
          if ! gcloud artifacts repositories describe $REPO_NAME --location=${{ vars.GCP_REGION_EU }} --project=${{ secrets.GCP_PROJECT_ID }} > /dev/null 2>&1; then
            echo "Artifact Registry repository $REPO_NAME does not exist. Creating..."
            gcloud artifacts repositories create $REPO_NAME \
              --repository-format=docker \
              --location=${{ vars.GCP_REGION_EU }} \
            --project=${{ secrets.GCP_PROJECT_ID }}
          else 
            echo "Artifact Registry repository $REPO_NAME already exists."
          fi
      
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      # --- Terraform Backend Setup ---
      # This step ensures the GCS bucket for Terraform state exists before Terraform init
      - name: Ensure Terraform State Bucket Exists
        run: |
          # Assign shell variables from GitHub Actions contexts/environment
          # Using env variables set at the job level (except for REGION, directly from vars)
          BUCKET_NAME="${{ env.TF_STATE_BUCKET }}"
          PROJECT_ID="${{ env.GCP_PROJECT_ID }}"
          # Accessing vars.GCP_REGION_EU directly here as env.GCP_REGION was unstable in previous logs for this step
          REGION="${{ vars.GCP_REGION_EU }}"

          # Debugging output to check variable values (Recommended for troubleshooting)
          echo "--- Debugging Bucket Creation Variables ---"
          echo "Bucket Name: ${BUCKET_NAME}"
          echo "Project ID: ${PROJECT_ID}"
          echo "Region from vars.GCP_REGION_EU: ${{ vars.GCP_REGION_EU }}" # Print raw vars context value
          echo "Region shell variable value: ${REGION}" # Print the value assigned to the shell variable
          echo "------------------------------------------"

          # Check if the bucket exists
          if gcloud storage buckets describe "gs://${BUCKET_NAME}" --project="${PROJECT_ID}" > /dev/null 2>&1; then
            echo "Terraform state bucket gs://${BUCKET_NAME} already exists."
          else
            echo "Terraform state bucket gs://${BUCKET_NAME} does not exist. Creating..."
            # Create the bucket with uniform bucket-level access for security
            # Using the shell variables defined above
            gcloud storage buckets create "gs://${BUCKET_NAME}" \
              --project="${PROJECT_ID}" \
              --location="${REGION}" \
              --uniform-bucket-level-access

            if [ $? -eq 0 ]; then
              echo "Bucket gs://${BUCKET_NAME} created successfully."
            else
              echo "Error creating bucket gs://${BUCKET_NAME}."
              exit 1
            fi
          fi

##### End of Terraform Backend Setup #####

  build_and_push_image:
    name: Build and Push Docker Image
    needs: [prepare_backend]
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ vars.GCP_REGION_EU }}
      GCP_ARTIFACT_IMAGE_NAME: ${{ vars.GCP_ARTIFACT_IMAGE_NAME }}
      # This should match what Terraform expects for archie_mcp_image_uri
      IMAGE_TO_PUSH: ${{ vars.GCP_REGION_EU }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/archie-backend/${{ vars.GCP_ARTIFACT_IMAGE_NAME }}:${{ github.sha }}
      ENVIRONMENT: ${{ github.ref_name }}
    # If you want to pass the exact pushed URI to Terraform (more robust) outputs:
    #   image_uri: ${{ steps.tag_and_build_image.outputs.image_uri_with_sha }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set environment-specific backend URL
        run: echo "Backend URL replacement will now happen in the deploy_frontend job."

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        id: auth
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build Docker Image
        id: tag_and_build_image
        run: |
          echo "Building and tagging image as: ${{ env.IMAGE_TO_PUSH }}"
          docker build -t "${{ env.IMAGE_TO_PUSH }}" -f ./functions/archiemcp/Dockerfile ./functions/archiemcp/
          # If using outputs:
          # echo "image_uri_with_sha=${{ env.IMAGE_TO_PUSH }}" >> $GITHUB_OUTPUT

      - name: Debug IMAGE_NAME (Corrected to IMAGE_TO_PUSH)
        run: |
          echo "IMAGE_TO_PUSH is: ${{ env.IMAGE_TO_PUSH }}"

      - name: Push Docker Image to Artifact Registry
        run: |
          docker push "${{ env.IMAGE_TO_PUSH }}"

#     - name: Deploy to Cloud Run
#       run: |
#         gcloud run deploy archie-mcp-${{ github.ref_name }} \
#           --image=${{ env.IMAGE_NAME }} \
#           --region=${{ env.GCP_REGION }} \
#           --project=${{ env.GCP_PROJECT_ID }} \
#           --allow-unauthenticated # For simplicity in the lab.  Restrict in production.

##### End of Build and Push Image #####

  deploy_infra:
    name: Deploy Infrastructure
    needs: [build_and_push_image]
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    env:
      GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ vars.GCP_REGION_EU }}
      TF_STATE_BUCKET: terraform-state-${{ github.ref_name }}-${{ secrets.GCP_PROJECT_NUMBER }}
      ENVIRONMENT: ${{ github.ref_name }}
    outputs: # Expose the service URI for other jobs
      archie_mcp_service_uri: ${{ steps.get_service_uri.outputs.SERVICE_URI }}
      # frontend_bucket_name: ${{ steps.get_frontend_bucket.outputs.BUCKET_NAME }} # Bucket name will be fetched in deploy_frontend


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        id: auth
        with:
          workload_identity_provider: ${{ env.GCP_WIF_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" \
            -backend-config="prefix=tfstate/${{ env.ENVIRONMENT }}"
        working-directory: infra/

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra/

      - name: Terraform Apply deletion_protection=false
        working-directory: infra/
        run: |
          terraform apply -auto-approve \
            -var="deployer_service_account_email=${{ env.GCP_SERVICE_ACCOUNT }}" \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="region=${{ env.GCP_REGION_EU }}" \
            -var="environment=${{ env.ENVIRONMENT }}" \
            -var-file="${{ github.ref_name }}.tfvars" \
            -var="github_workspace=${{ github.workspace }}" \
            -var="github_sha=${{ github.sha }}" \
            -var="archie_mcp_image_uri=${{ vars.GCP_REGION_EU }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/archie-backend/${{ vars.GCP_ARTIFACT_IMAGE_NAME }}:${{ github.sha }}"

      - name: Get Cloud Run Service URI
        id: get_service_uri
        working-directory: infra/
        run: |
          SERVICE_URI=$(terraform output -raw archiemcp_service_uri)
          echo "SERVICE_URI=${SERVICE_URI}" >> $GITHUB_OUTPUT
          echo "Cloud Run Service URI: ${SERVICE_URI}"

      - name: Update GitHub Secret with Cloud Run Service URI
        if: github.ref_name == 'main' || github.ref_name == 'qa' || github.ref_name == 'dev'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN has secrets:write permission
          SERVICE_URI: ${{ steps.get_service_uri.outputs.SERVICE_URI }}
        run: |
          SECRET_NAME=""
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            SECRET_NAME="BACKEND_URL_MAIN"
          elif [[ "${{ github.ref_name }}" == "qa" ]]; then
            SECRET_NAME="BACKEND_URL_QA"
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            SECRET_NAME="BACKEND_URL_DEV"
          fi

          if [ -z "$SECRET_NAME" ]; then
            echo "Error: Could not determine secret name for branch ${{ github.ref_name }}."
            exit 1
          fi
          echo "Updating secret ${SECRET_NAME} with value ${SERVICE_URI}"
          gh secret set "${SECRET_NAME}" -b"${SERVICE_URI}" --env "${{ github.ref_name }}"
##### End of Build and Push Image ######

  deploy_frontend:
    name: Deploy Frontend
    needs: [deploy_infra]
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    env:
      GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ vars.GCP_REGION_EU }}
      ENVIRONMENT: ${{ github.ref_name }}
      ARCHIE_MCP_SERVICE_URI_FROM_INFRA: ${{ needs.deploy_infra.outputs.archie_mcp_service_uri }}
      TF_STATE_BUCKET: terraform-state-${{ github.ref_name }}-${{ secrets.GCP_PROJECT_NUMBER }} # Added for terraform init

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        id: auth
        with:
          workload_identity_provider: ${{ env.GCP_WIF_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" \
            -backend-config="prefix=tfstate/${{ env.ENVIRONMENT }}"
        working-directory: infra/

      # No need for terraform validate or apply here if we are only uploading files
      # and the bucket is already created by deploy_infra.
      # We only need terraform output for the bucket name.

      - name: Get Frontend Bucket Name
        id: get_frontend_bucket
        working-directory: infra/
        run: |
          BUCKET_NAME=$(terraform output -raw frontend_storage_bucket_name)
          echo "BUCKET_NAME=${BUCKET_NAME}" >> $GITHUB_OUTPUT
          echo "Frontend GCS Bucket Name: ${BUCKET_NAME}"

      - name: Configure Frontend with Backend URL
        run: |
          URL_TO_SET="${{ env.ARCHIE_MCP_SERVICE_URI_FROM_INFRA }}"
          echo "Retrieved service URI from deploy_infra job: $URL_TO_SET"
          if [ -z "$URL_TO_SET" ]; then
            echo "Error: Backend URL (archie_mcp_service_uri from deploy_infra) is not set."
            exit 1
          fi
          echo "Replacing placeholder in frontend/index.html with $URL_TO_SET"
          sed -i "s|__BACKEND_URL__|$URL_TO_SET|g" frontend/index.html
          echo "Replacement complete. Verifying content (first 5 lines containing backendUrl):"
          grep 'backendUrl' frontend/index.html | head -n 5 || echo "backendUrl line not found after replacement or file is empty."

      - name: Upload Frontend to GCS
        working-directory: infra/
        run: |
          # The working-directory is infra/, but frontend files are at the root of the checkout.
          # So, we use relative paths from the root for gsutil.
          FRONTEND_BUCKET_NAME="${{ steps.get_frontend_bucket.outputs.BUCKET_NAME }}"
          echo "Uploading frontend files from ../frontend/ to gs://${FRONTEND_BUCKET_NAME}/"
          gsutil -m rsync -r -d ../frontend/ gs://${FRONTEND_BUCKET_NAME}/
          echo "Frontend deployment to GCS complete."